### ISSUE TITLE
Install SimbodyTargets-release.cmake

### ISSUE THREAD

**Issue by chrisdembia** [conda-forge/simbody-feedstock#19]
For other CMake projects to properly find Simbody, it is important that the conda installation includes the `SimbodyTargets-*.cmake` files (which get included by `SimbodyConfig.cmake`).

**Comment by moorepants** [comment]
Are these files generated by cmake on build? If so, where do I find them?

**Comment by chrisdembia** [comment]
They are installed into the `cmake` directory of the installation. I should have also mentioned: there's also a `SimbodyTargets.cmake`, in addition to the `SimbodyTargets-release.cmake`. In the build tree, they should be in `cmake/CMakeFiles/Export/cmake`.

**Comment by chrisdembia** [comment]
These are installed.
