### ISSUE TITLE
Simbody CMake Config files refer to incorrect path for openblas.lib.

### ISSUE THREAD

**Issue by chrisdembia** [conda-forge/simbody-feedstock#33]
Issue:

On Windows, The CMake SimbodyTargets*.cmake files refer to a full path to `openblas.lib` that is only valid when building the conda package, because that's what we specify for the `BUILD_USING_OTHER_LAPACK` CMake variable. We need to find a way to make the `BUILD_USING_OTHER_LAPACK` option more portable. The solution could be a bit messy.

Reported here: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=47&t=12028&p=33984. In this forum post, Andrea suggests linking statically.

**Comment by chrisdembia** [comment]
Relatedly, `openblas` might need to be in the `run` section. The forum post linked above mentions the need to manually install `openblas`.

**Comment by moorepants** [comment]
conda has the ability to change hard coded paths, but sometimes they need some manual attention in the feedstock build script. There are some issues in the conda build repo about paths on windows that seem to still be open too.

**Comment by chrisdembia** [comment]
Ah good point. Maybe I need to pay more attention to the messages generated by conda-build at the end of the build process.

**Comment by moorepants** [comment]
Static linking may be an option, but I think that dynamic linking is preferable. You can do this now: https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation to switch blas implementations in an environment.

**Comment by moorepants** [comment]
One more thought, maybe we should at a test to this feedstock that builds a some program that links to simbody and uses a function in its headers.

**Comment by chrisdembia** [comment]
Ah yeah that's a great idea.
