### ISSUE TITLE
Linux binaries are huge wrt to OSX and Windows

### ISSUE THREAD

**Issue by moorepants** [conda-forge/simbody-feedstock#7]
See: https://anaconda.org/conda-forge/simbody/files

I don't think that it should be a 93 mb download.

**Comment by jakirkham** [comment]
Yeah, that doesn't look good. Have you looked at the build logs? Are there gobs of PDFs or something similar getting installed?

**Comment by moorepants** [comment]
@sherm1, Any idea why this might be?

**Comment by moorepants** [comment]
The shared libraries (core files and built examples) add up:
![selection_056](https://cloud.githubusercontent.com/assets/276007/19710979/3b7c99da-9ae7-11e6-9bee-6fbd92252935.jpg)
Whereas on Windows, all the binaries are tiny in comparison:
![selection_057](https://cloud.githubusercontent.com/assets/276007/19710998/69d2a554-9ae7-11e6-8f84-ff268247d3f1.jpg)

**Comment by sherm1** [comment]
Hi, Jason. Looks like the libraries were generated with debug information. That can be removed with the `strip` command. Here is what I got in Ubuntu 16.04:
```
total 179M
-rwxrwxr-x 1 sherm sherm 29M Oct 25 20:36 libSimTKcommon.so.3.6
-rwxrwxr-x 1 sherm sherm 63M Oct 25 20:36 libSimTKmath.so.3.6
-rwxrwxr-x 1 sherm sherm 89M Oct 25 20:36 libSimTKsimbody.so.3.6
```
I ran `strip *` on those and then they look like this:
```
total 13M
-rwxrwxr-x 1 sherm sherm 3.5M Oct 25 20:36 libSimTKcommon.so.3.6
-rwxrwxr-x 1 sherm sherm 4.5M Oct 25 20:36 libSimTKmath.so.3.6
-rwxrwxr-x 1 sherm sherm 4.9M Oct 25 20:36 libSimTKsimbody.so.3.6
```

**Comment by moorepants** [comment]
My build script is here: https://github.com/conda-forge/simbody-feedstock/blob/master/recipe/build.sh. Is the default to build with debug info? If so, can I simply tell it to build in release mode?

**Comment by moorepants** [comment]
Also, I use the same build script for mac and linux, so why would one build with debug symbols and the other not?

**Comment by sherm1** [comment]
I think the default is RelWithDebInfo for Simbody. You can change it to Release. It's possible that it is still putting debug info in the Mac build but that it is much smaller there (clang vs gcc). You can tell if you run "strip" on the Mac and the files get even smaller.
